import ServerSidebar from "@/components/Custom/ServerSidebar/ServerSidebar";
import Sidebar from "@/components/Custom/MiniSidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex w-full h-screen overflow-y-hidden ">
        <Sidebar />
        <ServerSidebar />
        {children}
      </div>
    </>
  );
}
